use_frameworks!

platform :ios, '10.0'

target 'KirihaCodeKit_Example' do
  pod 'KirihaCodeKit', :path => '../'
  
  pod 'SnapKit'

  target 'KirihaCodeKit_Tests' do
    inherit! :search_paths

    
  end
end
